/*++

Copyright (c) Microsoft Corporation. All rights reserved.

Module Name:

    NetPowerOffloadList.h

Environment:

    user mode

NOTE: This header is generated by stubwork.

      To modify contents, add or remove <shared> or <umdf>
      tags in the corresponding .x and .y template files.

--*/

#pragma once

#ifndef WDF_EXTERN_C
  #ifdef __cplusplus
    #define WDF_EXTERN_C       extern "C"
    #define WDF_EXTERN_C_START extern "C" {
    #define WDF_EXTERN_C_END   }
  #else
    #define WDF_EXTERN_C
    #define WDF_EXTERN_C_START
    #define WDF_EXTERN_C_END
  #endif
#endif

WDF_EXTERN_C_START

typedef struct _NET_POWER_OFFLOAD_LIST
{
    ULONG Size;
    void * Reserved[4];
} NET_POWER_OFFLOAD_LIST;

inline
void
NET_POWER_OFFLOAD_LIST_INIT(
    _Out_ NET_POWER_OFFLOAD_LIST * List
)
{
    RtlZeroMemory(List, sizeof(*List));
    List->Size = sizeof(*List);
}
WDF_EXTERN_C_END

