/*++

Copyright (c) Microsoft Corporation. All rights reserved.

Module Name:

    NetWakeSource.h

Environment:

    user mode

NOTE: This header is generated by stubwork.

      To modify contents, add or remove <shared> or <umdf>
      tags in the corresponding .x and .y template files.

--*/

#pragma once

#ifndef WDF_EXTERN_C
  #ifdef __cplusplus
    #define WDF_EXTERN_C       extern "C"
    #define WDF_EXTERN_C_START extern "C" {
    #define WDF_EXTERN_C_END   }
  #else
    #define WDF_EXTERN_C
    #define WDF_EXTERN_C_START
    #define WDF_EXTERN_C_END
  #endif
#endif

WDF_EXTERN_C_START

typedef struct _NET_WAKE_SOURCE_BITMAP_PARAMETERS
{
    ULONG Size;
    ULONG Id;
    UCHAR const * Pattern;
    SIZE_T PatternSize;
    UCHAR const * Mask;
    SIZE_T MaskSize;
} NET_WAKE_SOURCE_BITMAP_PARAMETERS;

inline
void
NET_WAKE_SOURCE_BITMAP_PARAMETERS_INIT(
    _Out_ NET_WAKE_SOURCE_BITMAP_PARAMETERS * Parameters
)
{
    RtlZeroMemory(Parameters, sizeof(*Parameters));
    Parameters->Size = sizeof(*Parameters);
}

typedef struct _NET_WAKE_SOURCE_MEDIA_CHANGE_PARAMETERS
{
    ULONG Size;
    BOOLEAN MediaConnect;
    BOOLEAN MediaDisconnect;
} NET_WAKE_SOURCE_MEDIA_CHANGE_PARAMETERS;

inline
void
NET_WAKE_SOURCE_MEDIA_CHANGE_PARAMETERS_INIT(
    _Out_ NET_WAKE_SOURCE_MEDIA_CHANGE_PARAMETERS * Parameters
)
{
    RtlZeroMemory(Parameters, sizeof(*Parameters));
    Parameters->Size = sizeof(*Parameters);
}

typedef enum _NET_WAKE_SOURCE_TYPE {
    NetWakeSourceTypeBitmapPattern = 1,
    NetWakeSourceTypeMagicPacket,
    NetWakeSourceTypeMediaChange,
    NetWakeSourceTypePacketFilterMatch,
    NetWakeSourceTypeEapolPacket,
} NET_WAKE_SOURCE_TYPE;

WDF_EXTERN_C_END

